import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import vm from 'node:vm';
import { webcrypto } from 'node:crypto';

const source = await readFile(process.argv[2], 'utf8');
const messages = [], listeners = new Set(), failures = [];
const parent = { postMessage: (data, origin) => messages.push({ data, origin }) };
const window = { parent, addEventListener: (_, fn) => listeners.add(fn), removeEventListener: (_, fn) => listeners.delete(fn) };
const context = { window, URL, crypto: webcrypto, setTimeout, clearTimeout };
vm.runInNewContext(source.replace('export function', 'function') + '\nthis.factory = createNavigation;', context);
const identity = { version: 1, application_slug: 'sample', launch_nonce: 'nonce' };
const origin = 'https://platform.test';
const emit = (data, overrides = {}) => { for (const listener of listeners) listener({ source: parent, origin, data: { ...identity, ...data }, ...overrides }); };
let dirty = false, accepted = 0;
const adapter = context.factory({ applicationSlug: 'sample', launchNonce: 'nonce', platformOrigin: origin,
  isDirty: () => dirty, onFailure: error => failures.push(error), onAccepted: () => accepted++, timeoutMs: 40 });
await assert.rejects(adapter.navigate('m', 'm.main'), /尚未声明/);
emit({ type: 'zhuojian:host-ready', capabilities: ['navigation.v1'] }, { origin: 'https://evil.test' });
assert.equal(adapter.supportsNavigation(), false);
emit({ type: 'zhuojian:host-ready', capabilities: ['navigation.v1'], launch_nonce: 'stale' });
assert.equal(adapter.supportsNavigation(), false);
emit({ type: 'zhuojian:host-ready', capabilities: ['navigation.v1'] });
assert.equal(adapter.supportsNavigation(), true);
for (const value of ['../admin', '', 'x'.repeat(121), undefined]) await assert.rejects(adapter.navigate(value, 'm.main'));
let complete = false;
const navigation = adapter.navigate('m', 'm.main').then(() => { complete = true; });
await assert.rejects(adapter.navigate('m', 'm.main'), /重复/);
const request = messages.at(-1).data;
assert.equal(messages.at(-1).origin, origin);
const result = { ...request, type: 'zhuojian:navigate-result', status: 'accepted' };
emit(result, { source: {} }); assert.equal(accepted, 0);
emit(result); await Promise.resolve(); assert.equal(accepted, 1); assert.equal(complete, false);
emit({ ...result, status: 'completed', page_key: 'other' }); await Promise.resolve(); assert.equal(complete, false);
emit({ ...result, status: 'completed' }); await navigation; assert.equal(complete, true);
dirty = true;
emit({ type: 'zhuojian:prepare-leave', request_id: 'leave-0001' });
assert.equal(messages.at(-1).data.dirty, true);
dirty = false;
emit({ type: 'zhuojian:prepare-leave', request_id: 'leave-0002' });
assert.equal(messages.at(-1).data.dirty, false);
await assert.rejects(adapter.navigate('m', 'm.main'), /超时/);
assert.equal(failures.length, 1);
const pending = adapter.navigate('m', 'm.main'); adapter.dispose();
await assert.rejects(pending, /页面已离开/);
assert.equal(listeners.size, 0);
console.log('PASS adapter capability, identity, limits, acceptance/completion, dirty, timeout, cleanup');
